# Generated by Django 3.2.9 on 2021-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=500)),
                ('Last_name', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Cin', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Role', models.CharField(max_length=500)),
            ],
        ),
    ]
